{
 "title": "Mythical  Beasts - RED Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Duration - p95 latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mythical_request_times_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors - % of requests returning 5xx",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(mythical_request_times_count{status=~\"5..\"}[1m])) / sum(rate(mythical_request_times_count[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate - Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(mythical_request_times_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}